### PR TITLE
Some features

### LINKED ISSUE #2: Fish from other mods come out as the item.
You should add a json file that people can add their fish to, so that they come out as the mod.
You would have to specify the modid, the fish entity, the fish item, and that chance of it being caught.

### PR DESCRIPTION
**Pull request by Jab125**
Will fix #2 

Added:
Databased fish (specify what item and what fish in datapacks)

- Use `self.remove(Entity.RemovalReason.DISCARDED);` instead of tping the rod, (if the player is at 0,1000,0, umm)
- bumped version

### CODE REVIEW

**Review by Pyxrs — CHANGES_REQUESTED** [review]
image
Have you tested this change? I attempted to use a method like this previously but it didn't work

**Comment by Jab125** [comment]
> image Have you tested this change? I attempted to use a method like this previously but it didn't work

Yes, i've tested it and it works, if you somehow use the rod at 0, 1020, 0, with custom worldgen, then that hook is very visibly move

**Review by Jab125 — COMMENTED** [review]
:)

**Review by Pyxrs — APPROVED** [review]
yess

**Pull request merged**
